---
abstract: "Implements the Perl 6 'gather/take' control structure in Perl 5"
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
  - 'Damian Conway'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300032, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Syntax-Keyword-Gather
requires:
  Sub::Exporter::Progressive: 0
  Test::More: 0.94
resources:
  bugtracker: https://github.com/frioux/Syntax-Keyword-Gather/issues
  repository: git://github.com/frioux/Syntax-Keyword-Gather.git
version: 1.002002
