---
abstract: "Implements the Perl 6 'gather/take' control structure in Perl 5"
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
  - 'Damian Conway'
build_requires:
  Test::More: 0.94
generated_by: 'Dist::Zilla version 1.093290'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Syntax-Keyword-Gather
requires:
  Sub::Exporter: 0.980
resources:
  repository: http://github.com/frioux/Syntax-Keyword-Gather
version: 0.093420
